version: "2.1"
services:
  python-code-server:
    image: pythonserver
    container_name: python-code-server
    volumes:
      - ./workspace:/config/workspace
    ports:
      - 8888:8888
    restart: unless-stopped